name: Feature Request
description: File a feature request. 
title: '[FEATURE]: <Software> - <Summary>'
labels: ['FEATURE','TRIAGE']
body:

  - type: markdown
    attributes:
      value: <br>To expedite issue processing please search open and closed issues before submitting a new one. Existing issues often contain information about workarounds, resolution, or progress updates.

  - type: textarea
    attributes:
      label: Feature Description
      description: A short summary of the proposal with an introduction and the problem being solved by the proposed change. Include useful persona flows. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposal
      description: A precise statement of the proposed change. Including sub-paragrpahs and diagrams.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Rationale
      description: A discussion of alternate approaches that have been considered and the trade offs, advantages, and disadvantages of the chosen approach.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Affected components (optional)
      description: What known compoenents in the Open Edge platform would be impacted by this feature?

  - type: textarea
    attributes:
      label: Open issues (optional)
      description: A discussion of issues relating to this proposal for which the author does not know the solution. This section may be omitted if there are none.
